services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA} 
      MSSQL_PID: ${MSSQL_PID}
    ports:
      - "${MSSQL_TCP_PORT}:${MSSQL_TCP_PORT}"
    volumes:
      - sql_data_volume:/var/opt/mssql
    # restart: always
    networks:
      - productnetwork
  webapi:
    # build: 
    #   context: ./
    #   dockerfile: backend.dockerfile

    image: counterlogic/iot-back-end-stable
    ports:
      - "8080:8080"   # HTTP
      - "8081:8081"  # HTTPS
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - productnetwork
    restart: on-failure
  frontend:
    # container_name: frontend
    image: phongngolam/react-front-end
    build: 
      context: ./
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    networks:
      - productnetwork
    environment:
      - REACT_API_URL=http://backend:8080/api/
  mqtt:
    container_name: broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./passwd:/passwd
networks:
  productnetwork:

volumes:
  sql_data_volume:

