name: Build and Publish Docker Image

# Trigger the workflow on push to master or production branches
on:
  push:
    branches: ['master', 'production']

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v4

      # Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Determine the tag based on the branch
      - name: Set Docker Tag
        id: set-tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "TAG=stable" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/production" ]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      # Build and push Docker image with dynamic tag
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .  # Location of your Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/iot-web-frontend:${{ steps.set-tag.outputs.TAG }}
          # Optional: Add cache to speed up builds
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/iot-web-frontend:${{ steps.set-tag.outputs.TAG }}
          cache-to: type=inline
